import NavBar from './(components)/NavBar/NavBar';
import localFont from 'next/font/local';
import './(styles)/globals.scss';
import { getDictionary } from '../../../getDictionary';

const myFont = localFont({
  src: [
    {
      path: '../../../fonts/Ordina/Ordina-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../fonts/Ordina/Ordina-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-ordinaReg',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width,initial-scale=1.0',
};

export default async function RootLayout({ children, params }) {
  const dict = await getDictionary(params.lang);

  return (
    <html lang={params.lang} className={myFont.variable}>
      <body>
        <NavBar lang={params.lang} dict={dict} />
        {children}
      </body>
    </html>
  );
}
